# Generated by Django 4.2.1 on 2023-08-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0003_order_item_orderstatus_delete_table1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(default=0.0),
        ),
    ]
