# Generated by Django 4.2.1 on 2023-08-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0004_order_item_price_order_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=False)),
                ('orderTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderTax', models.IntegerField()),
                ('customerid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ordering.customer')),
                ('items', models.ManyToManyField(to='Ordering.order_item')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ordering.orderstatus')),
            ],
        ),
    ]
